name: Run Unit Tests

on: [push]

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci

      - run: npm run test
        id: run-tests
        continue-on-error: true  

      - name: Notify on test failure
        if: failure()  
        run: echo "🚨 The test workflow failed in the repository `${{ github.repository }}` on commit `${{ github.sha }}`."
